name: vllm_throughput_gpu
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - ccache
  - gxx
  - gxx_linux-64
  - gcc_linux-64
  - make
  - gperftools
  - intel-openmp
  - nsight-compute
  - pip
  - pip:
    - -r vllm_gpu/requirements/build/cuda.txt
    - -r vllm_gpu/requirements/cuda.txt
    - -r requirements.txt
variables:
  VLLM_TARGET_DEVICE: cuda
  VLLM_USE_PRECOMPILED: 1 # Don't recompile kernels
  PYTHONPATH: ./vllm_gpu # Declare library path
  VLLM_USE_DEEP_GEMM: 0 # Disable MoE optimization (requires deep_gemm compilation otherwise)
